[tools]
node = "latest"
bun = "latest"


[settings]
experimental = true


[tasks.build]
run = '''
bun install
bun run build
'''
description = "Build the project"

[tasks.preview]
run = "bun run preview"
description = "Preview the project"

[tasks.deploy]
run = '''
mise run build
surge dist/ publish docs.pratyay.qzz.io
'''
description = "GitHub Pages"
