name: ci

permissions:
  contents: read
  pages: write
  id-token: write
  actions: write
  artifact-metadata: write


on:
  workflow_dispatch:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: true
  MISE_TRUST_ALL: 1

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jdx/mise:latest
    steps:
      - name: Cache
        uses: actions/cache@main
        with:
          path: |
            ~/.cache/mise
            ~/.local/share/mise
          key: mise-${{ runner.os }}
          restore-keys: |
            mise-${{ runner.os }}

      - name: checkout
        uses: actions/checkout@main
      - run: |
          mise trust
          mise deps
          mise run deploy
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_CLI }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
